export { default as Home } from './Dashboard/Home'
export {default as AddEmployee } from './Dashboard/AddEmployee'
export {default as EditEmployee } from './Dashboard/EditEmployee'
export {default as Header } from './Dashboard/Header'
export {default as List } from './Dashboard/List'